modLoader = "javafml"
loaderVersion = "[47,)"
license = "Apache License 2.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "pedrorok.com "
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile= "/icon.png"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create"
mandatory=true
versionRange="[6.0.4,6.1.0)"
ordering="NONE"
side="BOTH"